### ISSUE TITLE
Trying to compile sketch and get error:

### ISSUE THREAD

**Issue by DominikBaer** [stan23/HB-LC-Sw2-FM#1]
Hi 
I have received following error messages when compiling the sketch: 

Arduino: 1.8.7 (Mac OS X), Board: "ATmega32, Standard, 2.7v, Disabled (default), 8 MHz internal"

In file included from /Users/dominikbaer1/Documents/Arduino/Beispiel_AskSinPP-master/examples/HM-LC-Sw2-FM/HM-LC-Sw2-FM.ino:10:0:
/Users/dominikbaer1/Documents/Arduino/libraries/EnableInterrupt/EnableInterrupt.h:1083:2: error: #error Unsupported Arduino platform
 #error Unsupported Arduino platform
  ^
/Users/dominikbaer1/Documents/Arduino/libraries/EnableInterrupt/EnableInterrupt.h:1254:2: error: #error Unsupported Arduino platform
 #error Unsupported Arduino platform
  ^
In file included from /Users/dominikbaer1/Documents/Arduino/Beispiel_AskSinPP-master/examples/HM-LC-Sw2-FM/HM-LC-Sw2-FM.ino:12:0:
/Users/dominikbaer1/Documents/Arduino/libraries/Low-Power-master/LowPower.h:148:6: error: #error "Please ensure chosen MCU is either 88, 168, 168P, 328P, 32U4, 2560 or 256RFR2."
     #error "Please ensure chosen MCU is either 88, 168, 168P, 328P, 32U4, 2560 or 256RFR2."
      ^
exit status 1
Error compiling for board ATmega32.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I receive following output from the board when connected over the programmer:
BN: Unknown board
VID: 16C0
PID: 2A9B
SN: Upload any sketch to obtain it

Can you give me some ideas? 
Do I need first to burn the fuses? I have not yet done that.

**Comment by stan23** [comment]
Hi Dominik,
ich glaube dass deine AskSinPP Lib zu alt ist.
Es muss mindestens dieser commit enthalten sein:
https://github.com/pa-pa/AskSinPP/commit/367bbe08d31c2fd24e7452f6ce74e003652ff981

Dann wird die EnableInterrupt gar nicht mehr inkludiert, weil sie den Mega32 nicht unterstützt.
Soweit zum Kompilieren.

Welchen Programmieradapter nutzt du? 
Die Fuses kann man vorher oder nachher setzen.
